# Generated by Django 4.0 on 2023-03-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'verbose_name_plural': 'alimentos'},
        ),
        migrations.AlterModelOptions(
            name='cicloproduccion',
            options={'verbose_name_plural': 'ciclos de produccion'},
        ),
        migrations.AlterModelOptions(
            name='mortalidad',
            options={'verbose_name_plural': 'mortalidades'},
        ),
    ]
