# Generated by Django 4.0 on 2023-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuales', '0002_alter_alimento_options_alter_cicloproduccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortalidad',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='mortalidad',
            name='mort_aves',
        ),
        migrations.RemoveField(
            model_name='mortalidad',
            name='mortalidad_acumulada',
        ),
        migrations.RemoveField(
            model_name='mortalidad',
            name='selec_aves',
        ),
        migrations.RemoveField(
            model_name='mortalidad',
            name='total_mortalidad_aves',
        ),
        migrations.AddField(
            model_name='mortalidad',
            name='acumulada_porcentaje',
            field=models.DecimalField(decimal_places=50, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='mortalidad',
            name='total_acumulada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mortalidad',
            name='total_semana',
            field=models.IntegerField(null=True),
        ),
    ]
