# Generated by Django 4.0 on 2023-04-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuales', '0008_alter_mortalidad_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mortalidad',
            name='user',
        ),
    ]
