# Generated by Django 4.0 on 2023-04-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('visuales', '0009_remove_alimento_user_remove_mortalidad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='mortalidad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username'),
        ),
    ]
