# Generated by Django 4.0 on 2023-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuales', '0013_alter_alimento_user_alter_cicloproduccion_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='visuales/images/')),
            ],
        ),
    ]
