# Generated by Django 4.0 on 2023-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuales', '0016_metasip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloproduccion',
            name='bodega',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
